---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Settings
- type: document
  path: src/_data/metadata.json
  label: General
- type: document
  path: src/_data/menu.json
  label: Menu
- type: heading
  label: Pages
- type: document
  path: src/pages/board_members.html
  label: Board members
- type: document
  path: src/pages/featured_articles.html
  label: Featured articles
- type: document
  path: src/pages/bylaws.md
  label: Bylaws
- type: document
  path: src/pages/logo.html
  label: Logo
- type: document
  path: src/pages/membership.html
  label: Membership
- type: document
  path: src/pages/sponsorship.html
  label: Sponsorship
- type: heading
  label: Text
- type: document
  path: src/_includes/text/front_page.html
  label: Front page
- type: heading
  label: Content
- type: document
  path: src/_data/board_members.json
  label: Board members
- type: directory
  path: src/posts
  label: News
  create: documents
  match: "**/*"
  exclude: "*.json"
- type: directory
  path: src/articles
  label: Featured articles
  create: documents
  match: "**/*"
  exclude: "*.json"
- type: directory
  path: src/groups
  label: EV groups in Denmark
  create: documents
  match: "**/*"
  exclude: "*.json"
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/src"
  working_dir: "/src"
  instant_preview_command: npm run preview
