backend:
  name: git-gateway
  branch: netlify_cms
media_folder: "src/images"
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", time_format: HH:mm:ssZ, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "articles"
    label: "Featured articles"
    folder: "src/articles"
    create: true
    identifier_field: article_name
    fields: 
      - {label: "Article title", name: "article_name", widget: "string"}
      - {label: "Authors", name: "authors", widget: "string"}
      - {label: "DOI", name: "doi", widget: "string"}
      - {label: "Article title", name: "link", widget: "string"}
      - {label: "Image", name: "journal_image", widget: "image"}
      - {label: "Background color", name: "color", widget: "color"}
      - {label: "Publish date", name: "published",  widget: "datetime", time_format: HH:mm:ssZ, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
  - label: "Metadata"
    name: "settings"
    files:
      - label: "Metadata"
        name: "metadata"
        file: "src/_data/metadata.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: URL, name: url, widget: string}
          - {label: Lanuage, name: language, widget: string}
          - {label: URL, name: news_url, widget: string}
          - {label: Title, name: description, widget: string}
          - {label: URL, name: source_code_url, widget: string}
          - label: Contact info
            name: contact_info
            widget: string
          - label: Footer info
            name: footer
            widget: string