---
label: Main settings
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Main title of webpage
- type: text
  name: url
  label: Main URL
  description: Main accessable URL.
- type: text
  name: language
  label: Lanuage
  default: en
- type: text
  name: description
  label: Description
  description: Description of Webpage
- type: field_group
  name: menu
  label: Menu items
  fields:
  - name: resources
    type: field_group_list
    fields:
    - name: text_field
      type: list
      config:
        use_select: false
        min: 
        max: 
      label: text_field
    - name: section
      type: list
      config:
        use_select: true
        min: 
        max: 
        source:
          type: documents
          section: pages
      label: section
    - name: pages
      type: list
      config:
        use_select: true
        min: 
        max: 
        source:
          type: pages
          section: pages
      label: pages
    config:
      min: 
      max: 
      labelField: 
    label: Resources
  description: Text of main menu items
- type: field_group
  name: contact_info
  label: contact_info
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: email
    label: email
- type: field_group
  name: footer
  label: Footer settings
  fields:
  - type: text
    name: copyright
    label: copyright
  - type: text
    name: contact
    label: contact
  - type: text
    name: source_text
    label: source_text
  - type: text
    name: source_url
    label: source_url
  - type: text
    name: admin_text
    label: admin_text
  - type: text
    name: admin_url
    label: admin_url
pages:
- src/_data/metadata.json
