# This workflow will install node dependencies and deploy site to dist folder.

name: Deploy to dist

on:
  push:
    branches: [develop]
    paths:
      - 'src/**.js}'
      - 'src/**.md'
      - 'src/**.html'
      - 'src/**.njk'

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repo/get files
      uses: actions/checkout@v2
      
    - name: Setup node
      uses: actions/setup-node@v2

    - name: Install packages
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Add .nojekyll file
      run: touch ./dist/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: develop_dist
        folder: 'dist'
        clean: true
        clean-exclude: |
          .forestry